version: '3'
services:
  myapp:
    container_name: catacamp
    restart: always
    build: .
    ports:
      - '3000:3000'
      - '3001:3001'
      - '4000:4000'
    links:
      - redis
      - mongo
  mongo:
    container_name: catacamp-mongo
    image: 'mongo:5'
    ports:
      - '27017:27017'
  redis:
    container_name: catacamp-redis
    image: 'redis:4.0.11'
    ports:
      - '6379:6379'